from typing import List, Dict, Any

def analyze_symptoms(symptoms: List[str]) -> Dict[str, Any]:
    """
    Analyze symptoms using a basic Ayurvedic rule engine (Mock AI).
    In production, this would use an LLM with RAG.
    """
    symptoms_lower = [s.lower() for s in symptoms]
    
    diagnosis = "General Imbalance"
    dosha_imbalance = []
    severity = "Mild"
    actions = ["Consult an Ayurvedic practitioner"]
    herbs = ["Triphala"]

    # Basic Rules
    if any(s in ['dry skin', 'anxiety', 'constipation', 'insomnia', 'bloating'] for s in symptoms_lower):
        dosha_imbalance.append("Vata")
        diagnosis = "Vata Aggravation"
        actions = ["Warm oil massage (Abhyanga)", "Eat warm, cooked foods", "Regular sleep routine"]
        herbs = ["Ashwagandha", "Brahmi"]

    if any(s in ['acne', 'heartburn', 'anger', 'inflammation', 'rashes'] for s in symptoms_lower):
        dosha_imbalance.append("Pitta")
        diagnosis = "Pitta Aggravation"
        actions = ["Cooling diet", "Avoid spicy foods", "Moonlight exposure"]
        herbs = ["Shatavari", "Amalaki", "Aloe Vera"]

    if any(s in ['weight gain', 'lethargy', 'congestion', 'mucus', 'depression'] for s in symptoms_lower):
        dosha_imbalance.append("Kapha")
        diagnosis = "Kapha Aggravation"
        actions = ["Daily exercise", "Light, dry foods", "Wake up early"]
        herbs = ["Trikatu", "Ginger", "Tulsi"]

    if len(symptoms) > 3:
        severity = "Moderate"
    if len(symptoms) > 5:
        severity = "High"

    if len(dosha_imbalance) > 1:
        diagnosis = f"Combined {', '.join(dosha_imbalance)} Imbalance"

    return {
        "diagnosis": diagnosis,
        "severity": severity,
        "dosha_imbalance": dosha_imbalance,
        "recommended_actions": actions,
        "recommended_herbs": herbs,
        "disclaimer": "This analysis is generated by AyurSuvidha for informational purposes only. Please consult a qualified Ayurvedic physician for medical advice."
    }
